### ISSUE TITLE
Add zsh support to prompt.sh

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/dotfiles#13]
Zsh has another method for formatting colors that must be added. See the
`__git_ps1.sh` script for how.

**Comment by 4zv4l** [comment]
Hi, I tried your script for my zsh prompt and it didn't work and I tried to mess a bit but I didn't succeed to make it works.
It looks like this : 
![image](https://user-images.githubusercontent.com/46655455/154360732-707db304-3af9-4af7-ab71-72ea83cfdebb.png)
![image](https://user-images.githubusercontent.com/46655455/154360793-ee932d25-fc3b-40ad-998b-f7bb3b36df45.png)
